package JFrame.Client;

import JFrame.Main;

/**
 * Pantalla que mostra les diferents opcions de la gestio de clients
 * @author FerranCliment - DAW2 - 2018
 */
public class MenuClients extends javax.swing.JFrame {

    /**
     * Creates new form MenuClients1
     */
    public MenuClients() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Gestio de clients");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baixa_client = new javax.swing.JButton();
        alta_client = new javax.swing.JButton();
        modificar_client = new javax.swing.JButton();
        consultar_client = new javax.swing.JButton();
        enrere = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("S2G1GestioClients");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 255, 204));

        baixa_client.setText("Baixa Client");
        baixa_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baixa_clientActionPerformed(evt);
            }
        });

        alta_client.setText("Alta Client");
        alta_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alta_clientActionPerformed(evt);
            }
        });

        modificar_client.setText("Modificar Clients");
        modificar_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_clientActionPerformed(evt);
            }
        });

        consultar_client.setText("Consultar Clients");
        consultar_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_clientActionPerformed(evt);
            }
        });

        enrere.setText("Enrere");
        enrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addComponent(enrere)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(modificar_client, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(baixa_client, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alta_client, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultar_client, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(alta_client)
                .addGap(18, 18, 18)
                .addComponent(consultar_client)
                .addGap(18, 18, 18)
                .addComponent(modificar_client)
                .addGap(18, 18, 18)
                .addComponent(baixa_client)
                .addGap(51, 51, 51)
                .addComponent(enrere)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Boto per anar a la pantalla de donat d'alta clients
     * @param evt 
     */
    private void alta_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alta_clientActionPerformed
         /*******************************************************************/
        AltaClients obj = new AltaClients(); 	//creem la nova finestra AltaClients
        obj.setVisible(true);                   //la fem visible
        dispose();                              //eliminem la finestra actual
        /*******************************************************************/
    }//GEN-LAST:event_alta_clientActionPerformed
    /**
     * Boto per anar a la pantalla de baixa de clients
     * @param evt 
     */
    private void baixa_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baixa_clientActionPerformed
        /*******************************************************************/
        BaixaClients obj = new BaixaClients(); 	//creem la nova finestra BaixaClients
        obj.setVisible(true);                           //la fem visible
        dispose();                                      //eliminem la finestra actual
        /*******************************************************************/
    }//GEN-LAST:event_baixa_clientActionPerformed
    /**
     * Boto per anar a la pantalla de consultar clients
     * @param evt 
     */
    private void consultar_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_clientActionPerformed
        /*******************************************************************/
        ConsultarClients obj = new ConsultarClients(); //creem la nova finestra ConsultarClients
        obj.setVisible(true);                           //la fem visible
        dispose();                                      //eliminem la finestra actual
        /*******************************************************************/

    }//GEN-LAST:event_consultar_clientActionPerformed
    /**
     * Boto per anar a la pantalla de modificar clients
     * @param evt 
     */
    private void modificar_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_clientActionPerformed

        /*******************************************************************/
        ModificarClients obj = new ModificarClients(); 	//creem la nova finestra ModificarClients
        obj.setVisible(true);                           //la fem visible
        dispose();                                      //eliminem la finestra actual
        /*******************************************************************/
    }//GEN-LAST:event_modificar_clientActionPerformed
    /**
     * Boto per anar enrere
     * @param evt 
     */
    private void enrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrereActionPerformed
        Main principal = new Main();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_enrereActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuClients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alta_client;
    private javax.swing.JButton baixa_client;
    private javax.swing.JButton consultar_client;
    private javax.swing.JButton enrere;
    private javax.swing.JButton modificar_client;
    // End of variables declaration//GEN-END:variables
}
