package JFrame.Incidencia;

import Biblioteques.Auxiliar;
import Biblioteques.Cercadors;
import Biblioteques.Config;
import ClassesPrincipals.Incidencies;
import Public.Public;
import java.awt.Color;
import java.io.IOException;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Pantalla per a modificar les dades d'una incidencia
 *
 * @author ivan morte
 */
public class Modificar_incidencies extends javax.swing.JFrame {

    /**
     * Creates new form Modificar_incidencies
     */
    int elements[];//guarda la posicio que a fet click el usuari
    int posicio;
    boolean carregar = false;//boolean per a actualitzar el text de la zona i usuari
    String dades_antigues;

    public Modificar_incidencies() {
        initComponents();
        setTitle("Modificar incidencies");
        this.setLocationRelativeTo(null);
        /*Els camps de text de la zona i l'usuari els inicialitzem invisibles*/
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        Carregar.setEnabled(false);

        /*Asignem el valor false als booleans per a seleccionar zona/usuari*/
        Public.seleccio_zona = false;
        Public.seleccio_user = true;

        Color bg_color = Config.parseColor();           //variable per guardar el color
        getContentPane().setBackground(bg_color);       //aplicar el color al background

        /*Canviem la tipografia a la que hi ha en l'arxiu de fonts.txt*/
        Config.canviarFont(rootPane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TitolIncidencia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DescripcioIncidencia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SeleccionarUsuari = new javax.swing.JButton();
        SeleccionarZona = new javax.swing.JButton();
        DataIncidencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        Cercar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Carregar = new javax.swing.JButton();
        Enrere = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titol", "Descripcio", "Zona", "User", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Titol");

        jLabel2.setText("Descripcio");

        jLabel6.setText("Zona");

        jLabel7.setText("Usuari");

        SeleccionarUsuari.setText("Seleccionar usuari");
        SeleccionarUsuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarUsuariActionPerformed(evt);
            }
        });

        SeleccionarZona.setText("Seleccionar zona");
        SeleccionarZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarZonaActionPerformed(evt);
            }
        });

        jLabel5.setText("Data");

        Cercar.setText("Cercar");
        Cercar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CercarActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Carregar.setText("Carregar");
        Carregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarregarActionPerformed(evt);
            }
        });

        Enrere.setText("Enrere");
        Enrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Cercar)
                                        .addGap(18, 18, 18)
                                        .addComponent(Modificar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(SeleccionarUsuari, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                            .addComponent(SeleccionarZona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DataIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Carregar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Enrere))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TitolIncidencia)
                                    .addComponent(DescripcioIncidencia)))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TitolIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(DescripcioIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeleccionarZona)
                    .addComponent(jLabel6)
                    .addComponent(DataIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeleccionarUsuari)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Cercar)
                        .addComponent(Modificar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Carregar)
                        .addComponent(Enrere)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        Carregar.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked
    /**
     * carrega les dades del array al jtext field
     *
     * @param evt
     */
    private void CarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarregarActionPerformed
        carregar = true;
        Modificar.setEnabled(true);
        SeleccionarZona.setEnabled(true);
        SeleccionarUsuari.setEnabled(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);

        getContentPane().add(Carregar);
        elements = jTable1.getSelectedRows();
        if (elements.length > 1) {
            JOptionPane.showMessageDialog(null, "Massa opcions selecionades");
        } else {
            Object incidencies_aux = jTable1.getValueAt(jTable1.getSelectedRow(), 0);//indicencies_aux guarda el valor del ID de la incidencia, que en la taula es troba en la fila 'selectedRow' i columna 0
            posicio = -1;   //posicio -1 per si no troba res
            //if(){
            posicio = Cercadors.cerca_ID_incidencia(posicio, incidencies_aux);
            if (posicio == -1) {
                JOptionPane.showMessageDialog(null, "No s'ha trobat");
            } else {
                TitolIncidencia.setText(Public.arrayIncidencies.get(posicio).gettitolIncidencia());
                DescripcioIncidencia.setText(Public.arrayIncidencies.get(posicio).getdescripcioIncidencia());
                jLabel6.setText(Public.arrayIncidencies.get(posicio).getlloc());
                jLabel7.setText(Public.arrayIncidencies.get(posicio).getuser());
                DataIncidencia.setText(Public.arrayIncidencies.get(posicio).getdate());

                /*Guardem les dades antigues per escriure-les en els logs*/
                dades_antigues = Public.arrayIncidencies.get(posicio).gettitolIncidencia() + " "
                        + Public.arrayIncidencies.get(posicio).getdescripcioIncidencia() + " "
                        + Public.arrayIncidencies.get(posicio).getlloc() + " "
                        + Public.arrayIncidencies.get(posicio).getuser() + " "
                        + Public.arrayIncidencies.get(posicio).getdate();
            }
        }
        jLabel6.setText("Has seleccionat " + Public.arrayIncidencies.get(posicio).getlloc());
        jLabel7.setText("Has seleccionat " + Public.arrayIncidencies.get(posicio).getuser());

    }//GEN-LAST:event_CarregarActionPerformed
    /**
     * Boto per a confirmar la modificacio
     *
     * @param evt
     */
    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        try {
            if (!TitolIncidencia.getText().isEmpty() && !DescripcioIncidencia.getText().isEmpty() && !DataIncidencia.getText().isEmpty() && Auxiliar.isDateValid(DataIncidencia.getText())) {
                Public.arrayIncidencies.get(posicio).settitolIncidencia(TitolIncidencia.getText());
                Public.arrayIncidencies.get(posicio).setdescripcioIncidencia(DescripcioIncidencia.getText());
                Public.arrayIncidencies.get(posicio).setlloc(Public.zona_indicencia.getNom());
                Public.arrayIncidencies.get(posicio).setuser(Public.usuari_incidencia.getNom()
                        + " " + Public.usuari_incidencia.getCognom1() + " " + Public.usuari_incidencia.getCognom2());
                Public.arrayIncidencies.get(posicio).setdate(DataIncidencia.getText());

                /*Guardem les noves dades per escriure-les en el fitxer de logs*/
                String dades_noves = TitolIncidencia.getText() + " "
                        + DescripcioIncidencia.getText() + " "
                        + Public.zona_indicencia.getNom() + " "
                        + Public.usuari_incidencia.getNom() + " "
                        + Public.usuari_incidencia.getCognom1() + " "
                        + Public.usuari_incidencia.getCognom2() + " "
                        + DataIncidencia.getText() + " ";

                DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
                tabla.setRowCount(0);

                Iterator<Incidencies> iterando = Public.arrayIncidencies.iterator();
                while (iterando.hasNext()) {
                    Incidencies incidencia_aux = iterando.next();
                    tabla.addRow(new Object[]{incidencia_aux.getid(),
                        incidencia_aux.gettitolIncidencia(),
                        incidencia_aux.getdescripcioIncidencia(),
                        incidencia_aux.getlloc(),
                        incidencia_aux.getuser(),
                        incidencia_aux.getdate()
                    });
                }

                /*Missatge de confirmacio*/
                JOptionPane.showMessageDialog(null, "Canvis aplicats");

                TitolIncidencia.setText("");
                DescripcioIncidencia.setText("");
                DataIncidencia.setText("");
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);

                /*Imprimim en el fitxer de logs.txt*/
                String text_logs = "S'ha modificat la incidència ["+ dades_antigues
                        +"] per ["+ dades_noves +"]";
                Auxiliar.escriure_log(text_logs);
                
                Modificar.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Error en les dades introduïdes!");
            }

        } catch (Exception e) {
            Auxiliar.escriure_error("Error: " + e);
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Modificar.setEnabled(false);
        SeleccionarUsuari.setEnabled(false);
        SeleccionarZona.setEnabled(false);
        DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
        tabla.setRowCount(0);
        Iterator<Incidencies> iterando = Public.arrayIncidencies.iterator();

        while (iterando.hasNext()) {
            Incidencies incidencia_aux = iterando.next();
            tabla.addRow(new Object[]{incidencia_aux.getid(),
                incidencia_aux.gettitolIncidencia(),
                incidencia_aux.getdescripcioIncidencia(),
                incidencia_aux.getlloc(),
                incidencia_aux.getuser(),
                incidencia_aux.getdate()
            });

        }
        System.out.println(Public.arrayIncidencies.isEmpty());
    }//GEN-LAST:event_formWindowOpened
    /**
     * Boto per a fer una cerca
     *
     * @param evt
     */
    private void CercarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CercarActionPerformed
        DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
        String paraulaCercada;
        paraulaCercada = this.jTextField6.getText();    //guarda les dades del text field a una variable per comparar en les dades de la taula
        Cercadors.cercar_incidencia(tabla, paraulaCercada);
    }//GEN-LAST:event_CercarActionPerformed

    /**
     * Boto per a assignar una zona a una incidencia
     *
     * @param evt
     */
    private void SeleccionarZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarZonaActionPerformed
        Llistar_zona llistar = new Llistar_zona();
        llistar.setVisible(true);
    }//GEN-LAST:event_SeleccionarZonaActionPerformed

    /**
     * Boto per assignar un usuari a una incidencia
     *
     * @param evt
     */
    private void SeleccionarUsuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarUsuariActionPerformed
        Llistar_clients llistar = new Llistar_clients();
        llistar.setVisible(true);
    }//GEN-LAST:event_SeleccionarUsuariActionPerformed

    /**
     * Accio quan la finestra obte 'focus'
     *
     * @param evt
     */
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        /*System.out.println(Public.seleccio_zona);
        if (Public.seleccio_zona){
            jLabel6.setText("Has seleccionat "+Public.zona_indicencia.getNom());
        }
        System.out.println(Public.seleccio_user);
        if (Public.seleccio_user){
            jLabel7.setText("Has seleccionat "+Public.usuari_incidencia.getNom() + " " + Public.usuari_incidencia.getCognom1()
                         + " " + Public.usuari_incidencia.getCognom2());
        }*/
    }//GEN-LAST:event_formWindowGainedFocus

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    /**
     * Boto per anar enrere
     *
     * @param evt
     */
    private void EnrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrereActionPerformed
        setVisible(false);
        Incidencies_menu menu = new Incidencies_menu();
        menu.setVisible(true);
    }//GEN-LAST:event_EnrereActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_incidencies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            Auxiliar.escriure_error("Error: " + ex);             //Escribim l'error en el fitxer d'errors
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_incidencies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            Auxiliar.escriure_error("Error: " + ex);             //Escribim l'error en el fitxer d'errors
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_incidencies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            Auxiliar.escriure_error("Error: " + ex);             //Escribim l'error en el fitxer d'errors
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_incidencies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            Auxiliar.escriure_error("Error: " + ex);             //Escribim l'error en el fitxer d'errors
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar_incidencies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Carregar;
    private javax.swing.JButton Cercar;
    private javax.swing.JTextField DataIncidencia;
    private javax.swing.JTextField DescripcioIncidencia;
    private javax.swing.JButton Enrere;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton SeleccionarUsuari;
    private javax.swing.JButton SeleccionarZona;
    private javax.swing.JTextField TitolIncidencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
